/***** SUBQUERY 실습 *****/
SELECT ROUND(AVG(SALARY)) FROM EMPLOYEE E WHERE DEPT_CODE = E.DEPT_CODE;
SELECT EMP_NAME, SALARY FROM EMPLOYEE WHERE SALARY >= 3089821;
SELECT EMP_NAME, SALARY FROM EMPLOYEE WHERE SALARY >= (SELECT ROUND(AVG(SALARY)) FROM EMPLOYEE E WHERE DEPT_CODE = E.DEPT_CODE);

SELECT EMP_NAME, SALARY FROM EMPLOYEE WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEE);
SELECT EMP_NAME, SALARY FROM EMPLOYEE WHERE SALARY > (SELECT ROUND(AVG(SALARY)) FROM EMPLOYEE WHERE DEPT_CODE = 'D5');
SELECT EMP_NAME, SALARY FROM EMPLOYEE WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEE WHERE SALARY >= 3000000);
---> 서브 쿼리를 사용하여 특정 조건을 만족하는 값 중 최저 급여를 가진 값을 찾고,
----> 조건에 맞는 급여를 받는 직원을 외부 쿼리에서 조회한 것이다.
/*
서브 쿼리
(SELECT MIN(SALARY) ◀ 칼럼 중 최소 값 선택
FROM EMPLOYEE ◀ 찾을 데이터 테이블 선택
WHERE SALARY >= 3000000) ◀ 급여가 3백만원 이상인 행들 중에서 최소 값을 계산한 것

외부 쿼리
SELECT EMP_NAME, SALARY ◀ 최종적으로 눈으로 직접 볼 칼럼을 선택한 것
FROM EMPLOYEE ◀ 테이블 선택
WHERE SALARY ◀ 급여가 서브 쿼리에서 반환된 최소 급여와 같은 행들만 가져오는 것
*/

/* SELECT 를 사용한 SUB QUERY 실습*/
SELECT DEPT_TITLE, (SELECT COUNT(*) FROM EMPLOYEE E WHERE E.DEPT_CODE = D.DEPT_ID AND E.BONUS >= 0.2) AS "BONUS COUNT" FROM DEPARTMENT D;

SELECT DEPT_TITLE, (SELECT MAX(SALARY) FROM EMPLOYEE E WHERE E.DEPT_CODE = D.DEPT_ID AND E.DEPT_CODE IS NOT NULL) AS "최고 급여", (SELECT MIN(SALARY) FROM EMPLOYEE E WHERE E.DEPT_CODE = D.DEPT_ID AND E.DEPT_CODE IS NOT NULL) AS "최소 급여" FROM DEPARTMENT D;

SELECT D.DEPT_ID, 
(SELECT COUNT(*) FROM EMPLOYEE E WHERE E.DEPT_CODE = D.DEPT_ID) AS "직원 수" 
FROM DEPARTMENT D;

SELECT DEPT_TITLE, 
(SELECT COUNT(*) FROM EMPLOYEE E WHERE E.DEPT_CODE = D.DEPT_ID) AS "직원 수" 
FROM DEPARTMENT D 
WHERE (SELECT COUNT(*) FROM EMPLOYEE E WHERE E.DEPT_CODE = D.DEPT_ID) >= 5;