/***** DECODE 실습 *****/

SELECT STUDENT_NAME, SUBSTR(STUDENT_SSN, 8, 1), DECODE(SUBSTR(STUDENT_SSN, 8, 1), '1', '남자', '2', '여자') AS "성별" FROM TB_STUDENT;

SELECT EMP_NAME, DEPT_CODE, DECODE(SUBSTR(DEPT_CODE, 2, 1), '1', '인사관리부', '2', '회계관리부', '3', '마케팅부', '4', '국내영업부', '기타') AS "부서" FROM EMPLOYEE;

SELECT EMP_NAME, JOB_CODE, DECODE(SUBSTR(JOB_CODE, 2, 1), '1', '대표', '2', '부사장', '3', '부장', '4', '차장', '5', '과장', '6', '대리', '7', '사원', '알수없음') AS "직책" FROM EMPLOYEE;


/***** CASE WHEN THEN ELSE END 실습 *****/

SELECT EMP_NAME, SALARY, 
CASE 
WHEN SALARY >= 6000000 
THEN 'S1'
WHEN SALARY >= 5000000
THEN 'S2'
WHEN SALARY >= 4000000
THEN 'S3'
ELSE 'S4'
END 급여등급
FROM EMPLOYEE;

SELECT EMP_NAME, HIRE_DATE,
CASE
WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12) >= 20
THEN '20년 이상'
WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12) >= 10
THEN '10년 이상'
ELSE '10년 미만'
END 근속기간
FROM EMPLOYEE;